scripts/install-dev.sh

Update install script that patch Openshift Gitops Subscription to enable default instance which will prevent the custom instance we created to be deleted by operator.

Update install script 

---

.gitignore
ansible-playbooks/README.md
ansible-playbooks/playbooks/approve-private-endpoints.yml
ansible-playbooks/roles/import-managedcluster-default-invoke/tasks/main.yml

@cdoan1 to cleanup the README with the proper command (at least on fedora :) ) and to change ansible var.
~~AKS_RG~~ ->  AKS_NAME in `default .yml` file

updating doc and .gitignore for default file

---

cluster-bootstrap/alert-manager-config/overlay/dev-private/app-alertmanager-config.yaml
cluster-bootstrap/alert-manager-config/overlay/dev/app-alertmanager-config.yaml

Fix AOC_SLACK_API_URL value format and use latest version from vault

Update alert config to use latest vault version

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md

update the url

---

cluster-bootstrap/alert-manager-config/README.md
cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
cluster-bootstrap/alert-manager-config/overlay/dev-private/app-alertmanager-config.yaml
cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml

update the alertmgr conf

---

.github/workflows/pr-check.yml
scripts/ci-deploy-resources/pipeline.yaml
scripts/ci-deploy-resources/pipelinerun.yaml
scripts/ci-deploy-resources/sample-pvc.yaml
scripts/ci-deploy-resources/secrets.yaml
scripts/ci-deploy-resources/tasks.yaml
scripts/ci-deploy.sh

Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
Triggers on PRs after adding the `ok-to-test` label when merged.
Requires secrets to be set in Github repo in order to run
The GH action can be tested here - https://github.com/zkayyali812/acm-aap-aas-operations/pull/23
By adding the `ok-to-test` label.

PR Test GH Action Pipeline

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
cluster-bootstrap/alertmanager-to-github/base/alert-blocklist.yaml
cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
cluster-bootstrap/alertmanager-to-github/base/kustomization.yaml
cluster-bootstrap/alertmanager-to-github/base/secret.yaml
cluster-bootstrap/alertmanager-to-github/base/service.yaml
cluster-bootstrap/alertmanager-to-github/overlay/dev/kustomization.yaml
cluster-bootstrap/alertmanager-to-github/overlay/dev/set-args.yaml
cluster-bootstrap/alertmanager-to-github/overlay/stage/kustomization.yaml
cluster-bootstrap/alertmanager-to-github/overlay/stage/set-args.yaml
cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/application.yaml
cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/kustomization.yaml
cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/application.yaml
cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/kustomization.yaml

- remove the ignored-alerts receiver
- add new App for tool alertmanager-to-github
- add a blocklist to ignore the alert when create the issue

add the alertmanager-to-github to auto-create issue for alert

---

cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml

add proxy for webhook

---

ansible-playbooks/Makefile
ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/create.yml
ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/delete.yml
ansible-playbooks/roles/restore-hub/tasks/main.yml
ansible-playbooks/roles/restore-hub/templates/managedcluster.yml
ansible-playbooks/roles/restore-hub/templates/restore-hub.yml

@cdoan1 @andreadecorte @zkayyali812 here is a working restore

To fix restore issues (partial commit and other problems)

---

ansible-playbooks/playbooks/bastion.yml
ansible-playbooks/roles/bastion-ocp4-facts/tasks/main.yml
ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
ansible-playbooks/roles/bastion-setup/tasks/main.yml

Extract ocp4 facts in a dedicated role for better sharing

Register RHEL with cluster name instead of just bastion for better clarity

---

OWNERS
cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml

update the cronjob version to v1

---

cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
tools/aap-metric-checker/aap-metric-checker-policy.yaml

update the image tag

---

cluster-bootstrap/openshift-gitops/config/Dockerfile

revert dockerfile

---

cluster-bootstrap/group-sync/overlay/dev/github-access-token.yaml
cluster-bootstrap/group-sync/overlay/dev/github-group-sync.yaml
cluster-bootstrap/group-sync/overlay/dev/kustomization.yaml

Config group sync operator to auto sync the team named `aap-aas-admin` in the org `ACM-APP-SRE`. So we don't need manually maintains a group yaml which will be make used by SSO.

Config group sync operator

---

cluster-bootstrap/openshift-config/overlay/local/kustomization.yaml
cluster-bootstrap/patch-operator/overlay/local/kustomization.yaml

Add local overlay for patch-operator and openshift-config

Add local overlay for patch-operator and openshift-config

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
cluster-bootstrap/multicluster-observability/base/custom-metrics/custom-metrics.yaml

- update the alertmgr conf
- add a new alert
- update the team tag for alert
- add a new custom metric to collect ns metrics

add new alert to monitor the managedcluster

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md

update alert interval

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml

add new alert for aap metric endpoint

---

ansible-playbooks/README.md
ansible-playbooks/roles/bastion-setup/tasks/main.yml
ansible-playbooks/roles/bastion-setup/vars/main.yml

Ref: https://github.com/ansible/awx/issues/1965

Change vars from dict to flat list as not supported by AWX injector

---

cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
scripts/ci-deploy-resources/tasks.yaml
tools/aap-metric-checker/aap-metric-checker-policy.yaml

https://issues.redhat.com/browse/AAP-3897

update image tag to digest

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
cluster-bootstrap/alertmanager-to-github/base/body.tmpl
cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml

https://issues.redhat.com/browse/AAP-3900

Disable group and update policy alerts

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml

- filter the AOC alert and only send the AOC alert to AOC private channel
- add a new receiver to receive the AOC alert for ACM SRE

add new receiver and update the receiver conf

---

ansible-playbooks/playbooks/vars/vars-rhaapprod.yml

* minor tweaks to the settings

update prod settings

---

ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
ansible-playbooks/playbooks/add-private-link-acm.yml
ansible-playbooks/playbooks/vars/vars-rhaap.yml

* fine tune the rhaap vars
* add template to create private link
* refactor playbook to reduce extra-vars requirements
* update project to update on launch = true

update rhaap vars file

---

ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml

This is useful when recreating a cluster with the same name

Improve kubeconfig upload to take into account changes

---

ansible-playbooks/playbooks/import-aap-aks-collection.yml
ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/create.yml

* This is the modification for the playbook to be invoked from AAP
* Includes all commands converted to azure module
* This first part is setting up the network link between AKS and the ACM HUB
* It will require passing in the AKS info, but then the next step is to link this up with dynamic inventory

update import part 1

---

tools/aap-metric-simulator/README.md
tools/aap-metric-simulator/manifests/automation-controller-auth.yaml
tools/aap-metric-simulator/manifests/deployment.yaml
tools/aap-metric-simulator/manifests/kustomization.yaml
tools/aap-metric-simulator/manifests/service.yaml
tools/aap-metric-simulator/manifests/servicemonitor.yaml

add servicemonitor and update the doc

---

tools/aap-metric-simulator/README.md
tools/aap-metric-simulator/manifests/automation-controller-admin-password.yaml
tools/aap-metric-simulator/manifests/kustomization.yaml

add secret for aap

---

cluster-bootstrap/prometheus-config/overlay/dev/aap-prom-conf-policy.yaml
tools/aap-metric-simulator/manifests/service.yaml
tools/aap-metric-simulator/manifests/servicemonitor.yaml

update the servicemonitor port

---

cluster-bootstrap/acm/overlay/testing/subscription.yaml

upgrade the testing to 2.5

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
cluster-bootstrap/multicluster-observability/overlay/dev/aap-alerts.yaml

- https://issues.redhat.com/browse/AAP-4092
- https://issues.redhat.com/browse/AAP-4118

update the alertconf and alert

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml

https://issues.redhat.com/browse/AAP-4197

disable KubeStateMetricsListErrors

---

cluster-bootstrap/argocd-apps/dev/openshift-config/application.yaml
cluster-bootstrap/argocd-apps/local/openshift-config/application.yaml
cluster-bootstrap/argocd-apps/prod/openshift-config/application.yaml
cluster-bootstrap/argocd-apps/testing/openshift-config/application.yaml
cluster-bootstrap/openshift-config/base/policy-openshift-cluster-version.yaml

https://issues.redhat.com/browse/AAP-3753

Disable pruning on openshift-config Argo app as it interferes with policies

---

cluster-bootstrap/acm/base/kustomization.yaml
cluster-bootstrap/acm/base/mce-namespace.yaml
cluster-bootstrap/acm/overlay/local/kustomization.yaml

Add mce namespace creating for fresh install.

Add mce namespace

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
cluster-bootstrap/prometheus-config/base/kustomization.yaml

update alerts interval and kustomization ns

---

ansible-playbooks/playbooks/add-private-link-acm.yml
ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/main.yml

As we already do it in the installer so this is safe to skip
Add also a fake host for localhost inventory

Skip subnet patching if we have a NAT Gateway created with ocp4-ipi installer

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml

https://issues.redhat.com/browse/AAP-4478

add a receiver to mute alert

---

cluster-bootstrap/alertmanager-to-github/overlay/dev/patch-secret-anno-for-vault.yaml

update dev GH token

---

cluster-bootstrap/alertmanager-to-github/overlay/prod/patch-secret-anno-for-vault.yaml

update GH token for prod

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts-policy.yaml

add more metadata to alert

---

cluster-bootstrap/multicluster-observability/base/deploy/multiclusterobservability.yaml

https://issues.redhat.com/browse/AAP-4351

set alertmgr replica to 1

---

cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml

https://issues.redhat.com/browse/AAP-4141

add inhibit_rules

---

cluster-bootstrap/multicluster-observability/base/custom-metrics/custom-metrics.yaml
cluster-bootstrap/multicluster-observability/base/dashboard/aap-pod-uptime.yaml
cluster-bootstrap/multicluster-observability/base/kustomization.yaml

https://issues.redhat.com/browse/AAP-4430

AAP uptime dashboard

---

tools/ansible-execution-environments/README.md
tools/ansible-execution-environments/azure_ee_supported_1.13.0/context/Containerfile
tools/ansible-execution-environments/azure_ee_supported_1.13.0/context/_build/requirements.txt
tools/ansible-execution-environments/azure_ee_supported_1.13.0/context/_build/requirements.yml
tools/ansible-execution-environments/azure_ee_supported_1.13.0/execution-environment.yml
tools/ansible-execution-environments/azure_ee_supported_1.13.0/requirements.txt
tools/ansible-execution-environments/azure_ee_supported_1.13.0/requirements.yml

Base is aligned with Ansible SRE EE for better testing and a possible merge in the future

Bump Ansible EE to latest version and add stolostron.ocm

---

cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml

add crb for aap servicemonitor

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts-policy.yaml
cluster-bootstrap/multicluster-observability/base/custom-metrics/custom-metrics.yaml

remove the AAPMetricMissing alert

---

cluster-bootstrap/multicluster-observability/base/custom-metrics/custom-metrics.yaml

add policy metric

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts-policy.yaml

filter aap job when monitor the AAP pod status

---

cluster-bootstrap/acm/overlay/dev/kustomization.yaml
cluster-bootstrap/acm/overlay/dev/multiclusterhub.yaml
cluster-bootstrap/acm/overlay/testing/kustomization.yaml
cluster-bootstrap/acm/overlay/testing/multiclusterhub.yaml

https://issues.redhat.com/browse/AAP-4742

Activate ManagedServiceAccount on the hub

---

cluster-bootstrap/multicluster-observability/base/dashboard/aap-pod-uptime.yaml

add ep dashboard

---

cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts-policy.yaml

only monitor the container restarts in an hour
